import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/react/components/core/header/header';

const inter = Inter({ subsets: ['latin'] });

const phrases = {
  appDescription: 'Generated by create next app',
  appTitle: 'Create Next App',
} as const;

export const metadata: Metadata = {
  description: phrases.appDescription,
  title: phrases.appTitle,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
