import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ChakraProvider } from '@chakra-ui/react';

import { Header } from '@/react/core/header/header';

const globalStyles = {
  app: 'app',
} as const;

const phrases = {
  appDescription: 'Generated by create next app',
  appTitle: 'Create Next App',
} as const;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: phrases.appDescription,
  title: phrases.appTitle,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <div className={globalStyles.app}>
            <Header />
            {children}
          </div>
        </ChakraProvider>
      </body>
    </html>
  );
}
