// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/exampleMessage.proto
// Protobuf Java Version: 4.28.1

package protobuf.example;

public final class ExampleMessage {
  private ExampleMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      ExampleMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExampleRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.example.ExampleRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string query = 1;</code>
     * @return The query.
     */
    java.lang.String getQuery();
    /**
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>int32 page_number = 2;</code>
     * @return The pageNumber.
     */
    int getPageNumber();
  }
  /**
   * Protobuf type {@code protobuf.example.ExampleRequest}
   */
  public static final class ExampleRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.example.ExampleRequest)
      ExampleRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        ExampleRequest.class.getName());
    }
    // Use ExampleRequest.newBuilder() to construct.
    private ExampleRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ExampleRequest() {
      query_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.example.ExampleMessage.ExampleRequest.class, protobuf.example.ExampleMessage.ExampleRequest.Builder.class);
    }

    public static final int QUERY_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object query_ = "";
    /**
     * <code>string query = 1;</code>
     * @return The query.
     */
    @java.lang.Override
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
    private int pageNumber_ = 0;
    /**
     * <code>int32 page_number = 2;</code>
     * @return The pageNumber.
     */
    @java.lang.Override
    public int getPageNumber() {
      return pageNumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(query_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, query_);
      }
      if (pageNumber_ != 0) {
        output.writeInt32(2, pageNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(query_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, query_);
      }
      if (pageNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, pageNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.example.ExampleMessage.ExampleRequest)) {
        return super.equals(obj);
      }
      protobuf.example.ExampleMessage.ExampleRequest other = (protobuf.example.ExampleMessage.ExampleRequest) obj;

      if (!getQuery()
          .equals(other.getQuery())) return false;
      if (getPageNumber()
          != other.getPageNumber()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getPageNumber();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protobuf.example.ExampleMessage.ExampleRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protobuf.example.ExampleMessage.ExampleRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.example.ExampleMessage.ExampleRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.example.ExampleMessage.ExampleRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.example.ExampleRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.example.ExampleRequest)
        protobuf.example.ExampleMessage.ExampleRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.example.ExampleMessage.ExampleRequest.class, protobuf.example.ExampleMessage.ExampleRequest.Builder.class);
      }

      // Construct using protobuf.example.ExampleMessage.ExampleRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        query_ = "";
        pageNumber_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleRequest_descriptor;
      }

      @java.lang.Override
      public protobuf.example.ExampleMessage.ExampleRequest getDefaultInstanceForType() {
        return protobuf.example.ExampleMessage.ExampleRequest.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.example.ExampleMessage.ExampleRequest build() {
        protobuf.example.ExampleMessage.ExampleRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.example.ExampleMessage.ExampleRequest buildPartial() {
        protobuf.example.ExampleMessage.ExampleRequest result = new protobuf.example.ExampleMessage.ExampleRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protobuf.example.ExampleMessage.ExampleRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.query_ = query_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pageNumber_ = pageNumber_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.example.ExampleMessage.ExampleRequest) {
          return mergeFrom((protobuf.example.ExampleMessage.ExampleRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.example.ExampleMessage.ExampleRequest other) {
        if (other == protobuf.example.ExampleMessage.ExampleRequest.getDefaultInstance()) return this;
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getPageNumber() != 0) {
          setPageNumber(other.getPageNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                query_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                pageNumber_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object query_ = "";
      /**
       * <code>string query = 1;</code>
       * @return The query.
       */
      public java.lang.String getQuery() {
        java.lang.Object ref = query_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string query = 1;</code>
       * @return The bytes for query.
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        java.lang.Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string query = 1;</code>
       * @param value The query to set.
       * @return This builder for chaining.
       */
      public Builder setQuery(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        query_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string query = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuery() {
        query_ = getDefaultInstance().getQuery();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string query = 1;</code>
       * @param value The bytes for query to set.
       * @return This builder for chaining.
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        query_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int pageNumber_ ;
      /**
       * <code>int32 page_number = 2;</code>
       * @return The pageNumber.
       */
      @java.lang.Override
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <code>int32 page_number = 2;</code>
       * @param value The pageNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPageNumber(int value) {

        pageNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.example.ExampleRequest)
    }

    // @@protoc_insertion_point(class_scope:protobuf.example.ExampleRequest)
    private static final protobuf.example.ExampleMessage.ExampleRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.example.ExampleMessage.ExampleRequest();
    }

    public static protobuf.example.ExampleMessage.ExampleRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExampleRequest>
        PARSER = new com.google.protobuf.AbstractParser<ExampleRequest>() {
      @java.lang.Override
      public ExampleRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExampleRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExampleRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.example.ExampleMessage.ExampleRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExampleResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.example.ExampleResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string results = 1;</code>
     * @return A list containing the results.
     */
    java.util.List<java.lang.String>
        getResultsList();
    /**
     * <code>repeated string results = 1;</code>
     * @return The count of results.
     */
    int getResultsCount();
    /**
     * <code>repeated string results = 1;</code>
     * @param index The index of the element to return.
     * @return The results at the given index.
     */
    java.lang.String getResults(int index);
    /**
     * <code>repeated string results = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the results at the given index.
     */
    com.google.protobuf.ByteString
        getResultsBytes(int index);

    /**
     * <code>int32 total_pages = 2;</code>
     * @return The totalPages.
     */
    int getTotalPages();
  }
  /**
   * Protobuf type {@code protobuf.example.ExampleResponse}
   */
  public static final class ExampleResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.example.ExampleResponse)
      ExampleResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        ExampleResponse.class.getName());
    }
    // Use ExampleResponse.newBuilder() to construct.
    private ExampleResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ExampleResponse() {
      results_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.example.ExampleMessage.ExampleResponse.class, protobuf.example.ExampleMessage.ExampleResponse.Builder.class);
    }

    public static final int RESULTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList results_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string results = 1;</code>
     * @return A list containing the results.
     */
    public com.google.protobuf.ProtocolStringList
        getResultsList() {
      return results_;
    }
    /**
     * <code>repeated string results = 1;</code>
     * @return The count of results.
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated string results = 1;</code>
     * @param index The index of the element to return.
     * @return The results at the given index.
     */
    public java.lang.String getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated string results = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the results at the given index.
     */
    public com.google.protobuf.ByteString
        getResultsBytes(int index) {
      return results_.getByteString(index);
    }

    public static final int TOTAL_PAGES_FIELD_NUMBER = 2;
    private int totalPages_ = 0;
    /**
     * <code>int32 total_pages = 2;</code>
     * @return The totalPages.
     */
    @java.lang.Override
    public int getTotalPages() {
      return totalPages_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < results_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, results_.getRaw(i));
      }
      if (totalPages_ != 0) {
        output.writeInt32(2, totalPages_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < results_.size(); i++) {
          dataSize += computeStringSizeNoTag(results_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getResultsList().size();
      }
      if (totalPages_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, totalPages_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.example.ExampleMessage.ExampleResponse)) {
        return super.equals(obj);
      }
      protobuf.example.ExampleMessage.ExampleResponse other = (protobuf.example.ExampleMessage.ExampleResponse) obj;

      if (!getResultsList()
          .equals(other.getResultsList())) return false;
      if (getTotalPages()
          != other.getTotalPages()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (37 * hash) + TOTAL_PAGES_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPages();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protobuf.example.ExampleMessage.ExampleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static protobuf.example.ExampleMessage.ExampleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.example.ExampleMessage.ExampleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.example.ExampleMessage.ExampleResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.example.ExampleResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.example.ExampleResponse)
        protobuf.example.ExampleMessage.ExampleResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.example.ExampleMessage.ExampleResponse.class, protobuf.example.ExampleMessage.ExampleResponse.Builder.class);
      }

      // Construct using protobuf.example.ExampleMessage.ExampleResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        results_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        totalPages_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.example.ExampleMessage.internal_static_protobuf_example_ExampleResponse_descriptor;
      }

      @java.lang.Override
      public protobuf.example.ExampleMessage.ExampleResponse getDefaultInstanceForType() {
        return protobuf.example.ExampleMessage.ExampleResponse.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.example.ExampleMessage.ExampleResponse build() {
        protobuf.example.ExampleMessage.ExampleResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.example.ExampleMessage.ExampleResponse buildPartial() {
        protobuf.example.ExampleMessage.ExampleResponse result = new protobuf.example.ExampleMessage.ExampleResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protobuf.example.ExampleMessage.ExampleResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          results_.makeImmutable();
          result.results_ = results_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.totalPages_ = totalPages_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.example.ExampleMessage.ExampleResponse) {
          return mergeFrom((protobuf.example.ExampleMessage.ExampleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.example.ExampleMessage.ExampleResponse other) {
        if (other == protobuf.example.ExampleMessage.ExampleResponse.getDefaultInstance()) return this;
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ |= 0x00000001;
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
        if (other.getTotalPages() != 0) {
          setTotalPages(other.getTotalPages());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureResultsIsMutable();
                results_.add(s);
                break;
              } // case 10
              case 16: {
                totalPages_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList results_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureResultsIsMutable() {
        if (!results_.isModifiable()) {
          results_ = new com.google.protobuf.LazyStringArrayList(results_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string results = 1;</code>
       * @return A list containing the results.
       */
      public com.google.protobuf.ProtocolStringList
          getResultsList() {
        results_.makeImmutable();
        return results_;
      }
      /**
       * <code>repeated string results = 1;</code>
       * @return The count of results.
       */
      public int getResultsCount() {
        return results_.size();
      }
      /**
       * <code>repeated string results = 1;</code>
       * @param index The index of the element to return.
       * @return The results at the given index.
       */
      public java.lang.String getResults(int index) {
        return results_.get(index);
      }
      /**
       * <code>repeated string results = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the results at the given index.
       */
      public com.google.protobuf.ByteString
          getResultsBytes(int index) {
        return results_.getByteString(index);
      }
      /**
       * <code>repeated string results = 1;</code>
       * @param index The index to set the value at.
       * @param value The results to set.
       * @return This builder for chaining.
       */
      public Builder setResults(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureResultsIsMutable();
        results_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string results = 1;</code>
       * @param value The results to add.
       * @return This builder for chaining.
       */
      public Builder addResults(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureResultsIsMutable();
        results_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string results = 1;</code>
       * @param values The results to add.
       * @return This builder for chaining.
       */
      public Builder addAllResults(
          java.lang.Iterable<java.lang.String> values) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string results = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResults() {
        results_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string results = 1;</code>
       * @param value The bytes of the results to add.
       * @return This builder for chaining.
       */
      public Builder addResultsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureResultsIsMutable();
        results_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int totalPages_ ;
      /**
       * <code>int32 total_pages = 2;</code>
       * @return The totalPages.
       */
      @java.lang.Override
      public int getTotalPages() {
        return totalPages_;
      }
      /**
       * <code>int32 total_pages = 2;</code>
       * @param value The totalPages to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPages(int value) {

        totalPages_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total_pages = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPages() {
        bitField0_ = (bitField0_ & ~0x00000002);
        totalPages_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.example.ExampleResponse)
    }

    // @@protoc_insertion_point(class_scope:protobuf.example.ExampleResponse)
    private static final protobuf.example.ExampleMessage.ExampleResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.example.ExampleMessage.ExampleResponse();
    }

    public static protobuf.example.ExampleMessage.ExampleResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExampleResponse>
        PARSER = new com.google.protobuf.AbstractParser<ExampleResponse>() {
      @java.lang.Override
      public ExampleResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExampleResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExampleResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.example.ExampleMessage.ExampleResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_example_ExampleRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_example_ExampleRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_example_ExampleResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_example_ExampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protobuf/exampleMessage.proto\022\020protobu" +
      "f.example\"4\n\016ExampleRequest\022\r\n\005query\030\001 \001" +
      "(\t\022\023\n\013page_number\030\002 \001(\005\"7\n\017ExampleRespon" +
      "se\022\017\n\007results\030\001 \003(\t\022\023\n\013total_pages\030\002 \001(\005" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_example_ExampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_example_ExampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_example_ExampleRequest_descriptor,
        new java.lang.String[] { "Query", "PageNumber", });
    internal_static_protobuf_example_ExampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_example_ExampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_example_ExampleResponse_descriptor,
        new java.lang.String[] { "Results", "TotalPages", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
