// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/example/exampleMessage.proto
// Protobuf Java Version: 4.28.1

package proto.example;

/**
 * Protobuf type {@code proto.example.ExampleResponse}
 */
public final class ExampleResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:proto.example.ExampleResponse)
    ExampleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      ExampleResponse.class.getName());
  }
  // Use ExampleResponse.newBuilder() to construct.
  private ExampleResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ExampleResponse() {
    results_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.example.ExampleMessage.internal_static_proto_example_ExampleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.example.ExampleMessage.internal_static_proto_example_ExampleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.example.ExampleResponse.class, proto.example.ExampleResponse.Builder.class);
  }

  public static final int RESULTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList results_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string results = 1;</code>
   * @return A list containing the results.
   */
  public com.google.protobuf.ProtocolStringList
      getResultsList() {
    return results_;
  }
  /**
   * <code>repeated string results = 1;</code>
   * @return The count of results.
   */
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated string results = 1;</code>
   * @param index The index of the element to return.
   * @return The results at the given index.
   */
  public java.lang.String getResults(int index) {
    return results_.get(index);
  }
  /**
   * <code>repeated string results = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the results at the given index.
   */
  public com.google.protobuf.ByteString
      getResultsBytes(int index) {
    return results_.getByteString(index);
  }

  public static final int TOTAL_PAGES_FIELD_NUMBER = 2;
  private int totalPages_ = 0;
  /**
   * <code>int32 total_pages = 2;</code>
   * @return The totalPages.
   */
  @java.lang.Override
  public int getTotalPages() {
    return totalPages_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < results_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, results_.getRaw(i));
    }
    if (totalPages_ != 0) {
      output.writeInt32(2, totalPages_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < results_.size(); i++) {
        dataSize += computeStringSizeNoTag(results_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getResultsList().size();
    }
    if (totalPages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalPages_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.example.ExampleResponse)) {
      return super.equals(obj);
    }
    proto.example.ExampleResponse other = (proto.example.ExampleResponse) obj;

    if (!getResultsList()
        .equals(other.getResultsList())) return false;
    if (getTotalPages()
        != other.getTotalPages()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_PAGES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalPages();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.example.ExampleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.ExampleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.ExampleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.ExampleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.ExampleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.ExampleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.ExampleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.example.ExampleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.example.ExampleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.example.ExampleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.example.ExampleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static proto.example.ExampleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.example.ExampleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.example.ExampleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.example.ExampleResponse)
      proto.example.ExampleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.example.ExampleMessage.internal_static_proto_example_ExampleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.example.ExampleMessage.internal_static_proto_example_ExampleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.example.ExampleResponse.class, proto.example.ExampleResponse.Builder.class);
    }

    // Construct using proto.example.ExampleResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      results_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      totalPages_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.example.ExampleMessage.internal_static_proto_example_ExampleResponse_descriptor;
    }

    @java.lang.Override
    public proto.example.ExampleResponse getDefaultInstanceForType() {
      return proto.example.ExampleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public proto.example.ExampleResponse build() {
      proto.example.ExampleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.example.ExampleResponse buildPartial() {
      proto.example.ExampleResponse result = new proto.example.ExampleResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(proto.example.ExampleResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        results_.makeImmutable();
        result.results_ = results_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalPages_ = totalPages_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.example.ExampleResponse) {
        return mergeFrom((proto.example.ExampleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.example.ExampleResponse other) {
      if (other == proto.example.ExampleResponse.getDefaultInstance()) return this;
      if (!other.results_.isEmpty()) {
        if (results_.isEmpty()) {
          results_ = other.results_;
          bitField0_ |= 0x00000001;
        } else {
          ensureResultsIsMutable();
          results_.addAll(other.results_);
        }
        onChanged();
      }
      if (other.getTotalPages() != 0) {
        setTotalPages(other.getTotalPages());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureResultsIsMutable();
              results_.add(s);
              break;
            } // case 10
            case 16: {
              totalPages_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList results_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureResultsIsMutable() {
      if (!results_.isModifiable()) {
        results_ = new com.google.protobuf.LazyStringArrayList(results_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string results = 1;</code>
     * @return A list containing the results.
     */
    public com.google.protobuf.ProtocolStringList
        getResultsList() {
      results_.makeImmutable();
      return results_;
    }
    /**
     * <code>repeated string results = 1;</code>
     * @return The count of results.
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated string results = 1;</code>
     * @param index The index of the element to return.
     * @return The results at the given index.
     */
    public java.lang.String getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated string results = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the results at the given index.
     */
    public com.google.protobuf.ByteString
        getResultsBytes(int index) {
      return results_.getByteString(index);
    }
    /**
     * <code>repeated string results = 1;</code>
     * @param index The index to set the value at.
     * @param value The results to set.
     * @return This builder for chaining.
     */
    public Builder setResults(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureResultsIsMutable();
      results_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string results = 1;</code>
     * @param value The results to add.
     * @return This builder for chaining.
     */
    public Builder addResults(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureResultsIsMutable();
      results_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string results = 1;</code>
     * @param values The results to add.
     * @return This builder for chaining.
     */
    public Builder addAllResults(
        java.lang.Iterable<java.lang.String> values) {
      ensureResultsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, results_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string results = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResults() {
      results_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string results = 1;</code>
     * @param value The bytes of the results to add.
     * @return This builder for chaining.
     */
    public Builder addResultsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureResultsIsMutable();
      results_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int totalPages_ ;
    /**
     * <code>int32 total_pages = 2;</code>
     * @return The totalPages.
     */
    @java.lang.Override
    public int getTotalPages() {
      return totalPages_;
    }
    /**
     * <code>int32 total_pages = 2;</code>
     * @param value The totalPages to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPages(int value) {

      totalPages_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_pages = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPages() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalPages_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.example.ExampleResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.example.ExampleResponse)
  private static final proto.example.ExampleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.example.ExampleResponse();
  }

  public static proto.example.ExampleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExampleResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExampleResponse>() {
    @java.lang.Override
    public ExampleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExampleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExampleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.example.ExampleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

