// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/example/exampleMessage.proto
// Protobuf Java Version: 4.28.1

package proto.example;

public interface ExampleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.example.ExampleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>int32 page_number = 2;</code>
   * @return The pageNumber.
   */
  int getPageNumber();
}
