// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/example/exampleMessage.proto
// Protobuf Java Version: 4.28.1

package proto.example;

public interface ExampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.example.ExampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string results = 1;</code>
   * @return A list containing the results.
   */
  java.util.List<java.lang.String>
      getResultsList();
  /**
   * <code>repeated string results = 1;</code>
   * @return The count of results.
   */
  int getResultsCount();
  /**
   * <code>repeated string results = 1;</code>
   * @param index The index of the element to return.
   * @return The results at the given index.
   */
  java.lang.String getResults(int index);
  /**
   * <code>repeated string results = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the results at the given index.
   */
  com.google.protobuf.ByteString
      getResultsBytes(int index);

  /**
   * <code>int32 total_pages = 2;</code>
   * @return The totalPages.
   */
  int getTotalPages();
}
