// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/example/exampleMessage.proto
// Protobuf Java Version: 4.28.1

package proto.example;

public final class ExampleMessage {
  private ExampleMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      ExampleMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_example_ExampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_example_ExampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_example_ExampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_example_ExampleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"proto/example/exampleMessage.proto\022\rpr" +
      "oto.example\"4\n\016ExampleRequest\022\r\n\005query\030\001" +
      " \001(\t\022\023\n\013page_number\030\002 \001(\005\"7\n\017ExampleResp" +
      "onse\022\017\n\007results\030\001 \003(\t\022\023\n\013total_pages\030\002 \001" +
      "(\005B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_example_ExampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_example_ExampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_example_ExampleRequest_descriptor,
        new java.lang.String[] { "Query", "PageNumber", });
    internal_static_proto_example_ExampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_example_ExampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_example_ExampleResponse_descriptor,
        new java.lang.String[] { "Results", "TotalPages", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
